name: Deploy Airflow DAGs (Local Docker)

on:
  push:
    branches: [ main ]
    paths:
      - 'dags/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy DAGs to Local Airflow via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "dags/"
          target: "/home/${{ secrets.DEPLOY_USER }}/Desktop/airflow-docker/dags"

      - name: Restart Airflow Containers (optional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ~/Desktop/airflow-docker
            docker compose restart airflow-scheduler airflow-webserver
